# Generated by Django 5.1.7 on 2025-03-24 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=64, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='database_manager.route')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('clouds', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('alerts', models.TextField(blank=True, null=True)),
                ('main_weather', models.CharField(max_length=64)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='database_manager.city')),
            ],
            options={
                'ordering': ('city', 'date'),
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RouteCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_routes', to='database_manager.city')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_cities', to='database_manager.route')),
            ],
            options={
                'ordering': ('route', 'position'),
                'unique_together': {('route', 'position')},
            },
        ),
    ]
