# Generated by Django 5.1.7 on 2025-03-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city_name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='forecastdata',
            options={'ordering': ['city', '-date']},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['route'], 'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['created_at'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='routecity',
            options={'ordering': ['route', 'position'], 'verbose_name': 'Route City', 'verbose_name_plural': 'Route Cities'},
        ),
        migrations.AlterUniqueTogether(
            name='forecastdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='routecity',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='visibility',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='forecastdata',
            constraint=models.UniqueConstraint(fields=('city', 'date'), name='unique_forecast_per_city'),
        ),
        migrations.AddConstraint(
            model_name='routecity',
            constraint=models.UniqueConstraint(fields=('route', 'position'), name='unique_route_position'),
        ),
    ]
