# Generated by Django 5.1.7 on 2025-03-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_alter_city_options_alter_forecastdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastdata',
            options={'ordering': ['city', '-date'], 'verbose_name': 'Forecast Data', 'verbose_name_plural': 'Forecast Data'},
        ),
    ]
