# Generated by Django 5.1.7 on 2025-04-08 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0003_alter_forecastdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecity',
            name='arrival_date',
            field=models.DateField(default=datetime.date(2025, 4, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routecity',
            name='departure_date',
            field=models.DateField(default=datetime.date(2025, 4, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='ends_at',
            field=models.DateField(default=datetime.date(2025, 4, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='starts_at',
            field=models.DateField(default=datetime.date(2025, 4, 8)),
            preserve_default=False,
        ),
    ]
