# Generated by Django 5.1.7 on 2025-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0004_routecity_arrival_date_routecity_departure_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastdata',
            name='visibility',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='humidity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='precipitation_probability',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='rain',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
    ]
