# Generated by Django 5.1.7 on 2025-04-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0005_remove_forecastdata_visibility_forecastdata_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastdata',
            name='alerts',
        ),
    ]
