# Generated by Django 5.1.7 on 2025-04-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0006_remove_forecastdata_alerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
    ]
