# Generated by Django 5.1.7 on 2025-05-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0008_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='icon',
            field=models.CharField(blank=True, help_text='Weather icon code from OpenWeatherMap', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='avg_temp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average temperature for the entire route', max_digits=5, null=True),
        ),
    ]
